### PR TITLE
Server render search results (search and channel pages)

### PR DESCRIPTION
**Pull request by jonkafton**
### What are the relevant tickets?

Closes: 
[Next.js: Search page: Prefetch API calls #6035](https://github.com/mitodl/hq/issues/6035)
[Next.js: Channel details page search: Prefetch API calls #6037](https://github.com/mitodl/hq/issues/6037)

### Description (What does it do?)

Prefetches search results for the search and channel details pages.

~~**Dependency on https://github.com/mitodl/mit-learn/pull/1846 to merge first** - this is need to apply user list and learning path relationships to the learning resources (server rendered resources won't have them).~~ Done.

~~This also needs https://github.com/mitodl/course-search-utils/pull/159 to be published before merging.~~ Done.

### How can this be tested?

On the search page /search and channel pages e.g. /c/topic/architecture, /c/department/media-arts-and-sciences, /c/unit/mitx, make various changes to the following, refreshing after each and ensuring that the search results are prerendered on the server with no calls made to /api/v1/learning_resources_search/ on first render and no prefetch warnings in the dev tools console:

- Search q text
- Filter facet selections
- Resource category tab selection
- Page selection

The search results should render ok on first load with JavaScript disabled in the dev tools debugger settings.

### Additional Context

Includes some refactoring to pull out `getSearchParams()` for reuse and provide a `requestSearchParams()` to convert Next.js parsed querystrings to our params for `learningResources.search()` API calls.

### CODE REVIEW

**Comment by jonkafton** [comment]
Converting to draft for now as dependent on https://github.com/mitodl/hq/issues/6032

**Comment by abeglova** [comment]
The search results don't seem to be pre-rendered but I'm guessing it's something wrong with my development environment. Will message you about it first thing tomorrow morning since you're probably done for the day

**Comment by jonkafton** [comment]
> The search results don't seem to be pre-rendered but I'm guessing it's something wrong with my development environment. Will message you about it first thing tomorrow morning since you're probably done for the day

I've removed a cache invalidation just now in https://github.com/mitodl/mit-learn/pull/1836/commits/8d52ff1d43dce54a877f54f7929794108f5b485c, which we no longer need and which would cause the search API to be called again on page load. This wouldn't have been preventing server rendering but could that have been the reason it didn't appear to be server rendering?

**Review by abeglova — APPROVED** [review]
LGTM - works great!

**Comment by jonkafton** [comment]
Converting to draft, pending https://github.com/mitodl/hq/issues/6163

**Pull request merged**
